export const works = [
  {
    title: 'IMOK, Owner',
    image: '/images/selectedWorks/owner.webp',
    year: '2022',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'owner',
  },
  {
    title: 'Whalerider',
    image: '/images/selectedWorks/whalerider.webp',
    year: '2022',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'whalerider',
  },

  {
    title: 'Bliss, Now',
    image: '/images/selectedWorks/bliss.webp',
    year: '2022',
    size: '20 x 30 in, 50.8 x 76.2 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'bliss',
  },
  {
    title: 'No Thyself',
    image: '/images/selectedWorks/noThyself.webp',
    year: '2022',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'no-thyself',
  },
  {
    title: 'Donut Eat Me, Please',
    image: '/images/selectedWorks/donut.webp',
    year: '2023',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'donut',
  },
  {
    title: 'Between Ferns',
    image: '/images/selectedWorks/ferns.webp',
    year: '2022',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'ferns',
  },
  {
    title: 'The Light Saw Me First',
    image: '/images/selectedWorks/gpaSays-1.webp',
    year: '2020',
    size: '16 x 20 in, 40.6 x 50.8 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'the-light-saw-me-first',
  },
  {
    title: 'Hide My Light',
    image: '/images/selectedWorks/gpaSays-2.webp',
    year: '2020',
    size: '16 x 20 in, 40.6 x 50.8 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'hide-my-light',
  },
  {
    title: 'Shining Light',
    image: '/images/selectedWorks/gpaSays-3.webp',
    year: '2020',
    size: '16 x 20 in, 40.6 x 50.8 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'shining-light',
  },
  {
    title: "I'm Crazy Today",
    image: '/images/selectedWorks/mostlyCrazy-1.webp',
    year: '2020',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'im-crazy-today',
  },
  {
    title: 'Out of Time',
    image: '/images/selectedWorks/strongForce-1.webp',
    year: '2019',
    size: '30 x 40 in, 76.2 x 101.6 cm',
    medium: 'Acrylic on canvas',
    links: null,
    slug: 'out-of-time',
  },
  {
    title: 'Lost in Motion',
    image: '/images/selectedWorks/movingThrough-1.webp',
    year: '2019',
    size: '16 x 20 in, 40.6 x 50.8 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'lost-in-motion',
  },
  {
    title: 'Wrestling Saved My Life',
    image: '/images/selectedWorks/movingThrough-2.webp',
    year: '2020',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'wrestling-saved-my-life',
  },
  {
    title: 'Who Are I',
    image: '/images/selectedWorks/whoseFace-2.webp',
    year: '2020',
    size: '16 x 20 in, 40.6 x 50.8 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'who-are-i',
  },
  {
    title: 'Abstract Times',
    image: '/images/selectedWorks/abstractTimes-1.webp',
    year: '2020',
    size: '16 x 20 in, 40.6 x 50.8 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'abstract-times',
  },
  {
    title: 'Friendship Cycle',
    image: '/images/selectedWorks/abstractTimes-2.webp',
    year: '2021',
    size: '24 x 36 in, 61 x 91.4 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'friendship-cycle',
  },
  {
    title: 'Anxious Again',
    image: '/images/selectedWorks/mostlyCrazy-3.webp',
    year: '2019',
    size: '9 x 11 in, 22.9 x 27.9 cm',
    medium: 'Pen on paper',
    links: null,
    slug: 'anxious-again',
  },
  {
    title: 'It Will Be Okay. It Will Be Okay',
    image: '/images/selectedWorks/mostlyCrazy-4.webp',
    year: '2019',
    size: '9 x 11 in, 22.9 x 27.9 cm',
    medium: 'Pen on paper',
    links: null,
    slug: 'it-will-be-okay',
  },
  {
    title: 'I Am Not Crazy',
    image: '/images/selectedWorks/mostlyCrazy-6.webp',
    year: '2020',
    size: '9 x 11 in, 22.9 x 27.9 cm',
    medium: 'Charcoal on paper',
    links: null,
    slug: 'i-am-not-crazy',
  },
  {
    title: 'Nude Pose 1',
    image: '/images/selectedWorks/nudePose-1.webp',
    year: '2020',
    size: '16 x 20 in, 40.6 x 50.8 cm',
    medium: 'Oil on canvas',
    links: null,
    slug: 'nude-pose-1',
  },
  {
    title: 'Whalerider Costume Design and Music Video',
    image: '/images/selectedWorks/whalerider-1.webp',
    year: '2023',
    size: 'Digital video',
    medium: 'Textile, paper mache, acrylic paint, video',
    links: [
      {
        url: 'https://www.youtube.com/watch?v=A2lM1jw5f8M',
        text: 'Watch the music video',
      },
      {
        url: 'https://open.spotify.com/album/2Lpo8E5FQWmI4Qipw0sTMy?si=mh-xVx3vToGtzql7sQo8pg',
        text: 'Listen to the EP',
      },
    ],
    slug: 'whalerider-music-video',
  },
];
